### Dot Product

In [3]:
import numpy as np

In [4]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

In [5]:
a1 = np.array(l1)
a2 = np.array(l2)

In [7]:
b = np.dot(a1, a2)
b

32

In [8]:
c = a1 @ a2
c

32

### Multidimensional arrays

In [19]:
a = np.array([[1, 2], [3, 4]])
a.shape

(2, 2)

In [17]:
print(a[1, 0])

3


In [23]:
print(np.diag(a))

[1 4]


### Indexing and slicing

In [25]:
a = np.array([[1, 2, 4, 5], [6, 7, 8, 9]])
a

array([[1, 2, 4, 5],
       [6, 7, 8, 9]])

In [29]:
print(a[-1, -2])

8


In [31]:
bool_index = a > 2
bool_index

array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
a = np.array([20, 31, 24, 52, 61, 72])
a

array([20, 31, 24, 52, 61, 72])

In [33]:
b = [1, 4, 5]
print(a[b])

[31 61 72]


In [34]:
c = np.argwhere(a%2==0).flatten()
print(a[c])

[20 24 52 72]


In [41]:
a = np.eye(4) # identity matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [51]:
a = np.arange(1, 7)
a
a.shape

(6,)

In [53]:
b = a.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

### Arange and reshape

In [57]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [58]:
b = a.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
b = a[:, np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [63]:
b.shape

(6, 1)

### Concatenation

In [71]:
a = np.array([1, 2, 4, 5])
b = np.array([4, 5, 6, 7])

In [75]:
c = np.vstack((a, b))
c

array([[1, 2, 4, 5],
       [4, 5, 6, 7]])